export const CHANGE_SHOW_FLAG = 'CHANGE_SHOW_FLAG'
export const CHANGE_FORCE_SHOW_FLAG = 'CHANGE_FORCE_SHOW_FLAG'
export const CHANGE_CURRENT_SONG = 'CHANGE_CURRENT_SONG'
export const CHANGE_PLAY_LIST = 'CHANGE_PLAY_LIST'