export const CHANGE_SONG_DETAIL = 'CHANGE_SONG_DETAIL'
export const CHANGE_LYRIC_LIST = 'CHANGE_LYRIC_LIST'
export const CHANGE_HOT_COMMENT = 'CHANGE_HOT_COMMENT'
export const CHANGE_SIMI_SONG = 'CHANGE_SIMI_SONG'